# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "EuiccPolicy"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_packages_apps_EuiccPolicy"

[[annotations]]
path = [".github/workflows/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["res/raw/*.json", "res/raw-w840dp-h480dp/*.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Google Inc."
SPDX-License-Identifier = "Apache-2.0"
